### ISSUE TITLE
L2Normalize Layer?

### ISSUE THREAD

**Issue by chenxi116** [Seth-Park/text_objseg_caffe#1]
Hi @Seth-Park . Thank you for the code. I was wondering which Caffe version are you using? The network structure uses L2Normalize layer, which I cannot find in the BVLC Caffe.
Thanks!

**Comment by Seth-Park** [comment]
Hi @chenxi116. Thank you for the interest. The L2Normalize code is from the Compact Bilinear Pooling implementation for [this paper](https://arxiv.org/abs/1511.06062.) 
You can compile the `feature/20160617_cb_softattention` branch in [this fork](https://github.com/akirafukui/caffe/) to use L2Normalize layer.
